services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://abitus-api.geia.vip}
        VITE_USE_MOCK: ${VITE_USE_MOCK:-false}
    ports:
      - "3000:80"